title: SSE Conference Deadlines
description: Countdowns to top conference deadlines.
author: Valentin Zieglmeier

domain: "deadlines.sse.in.tum.de"
baseurl: ""

github_username: tum-i4
github_repo: deadlines

include: ["ics"]
